stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.base:
  image: infnpd/mucoll-ilc-framework:1.4-centos8

build:
  extends: .base
  stage: build
  script:
    - echo "Hello World"
    - source /opt/ilcsoft/muonc/init_ilcsoft.sh # Setup ILC software
    - cmake -S . -B build -DBOOST_INCLUDEDIR=/usr/include/boost169 -DBOOST_LIBRARYDIR=/usr/lib64/boost169 -DCMAKE_CXX_STANDARD=11
    - cmake --build build
